import '@/styles/globals.css';
import Provider from '@components/provider';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children } : { children: React.ReactNode}) => {
  return (
      <html lang="en">
        <body>
          <Provider>
          <ToastContainer />
            {children}
          </Provider>
        </body>
      </html>
  )
}

export default RootLayout;


